#!/bin/bash

# Visual Learning Platform Mac App Launcher
# This script is executed when the app is double-clicked

# Get the app bundle directory
APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../" && pwd)"

# Open Terminal and run the launcher script
osascript -e "
tell application \"Terminal\"
    activate
    do script \"cd '$APP_DIR' && ./launcher/start-learning-platform.sh\"
end tell
"
